Computer:
  Product Information:
    - Brand
    - Model number
  Hardware Information:
    - Memory
    - Hard drive space
    - Is 32-bit or 64-bit?
    - CPU speed
  Software Information:
    - Computer name
    - Operating system
    - 32-bit or 64-bit?
    - Supports Yale domain login?
    - Encryption enabled?
    - Network shares

Router:
  Product Information:
    - Brand
    - Model number
  Hardware Information:
    - Wired or wireless?
    - Number of ethernet ports
  Software Information:
    - Wireless network encryption type

Printer:
  Product Information:
    - Brand
    - Model number
  Hardware Information:
    - Wired or wireless
    - Network enabled?